export const Data = [
  {
    id: 1,
    firstName: "สมชาย",
    lastName: "สายโค้ด",
    city: "Bangkok",
    company: "Tech Synergy",
    education: "Chulalongkorn University",
    role: "Frontend Developer",
    skills: ["React", "Tailwind", "TypeScript"],
    image: "https://i.pravatar.cc/150?u=1",
    description: "เน้นงาน UI/UX ที่ลื่นไหลและ Responsive",
    experience: "3 years",
  },
  {
    id: 2,
    firstName: "วิภา",
    lastName: "พารวย",
    city: "Chiang Mai",
    company: "Digital Nomad Co.",
    education: "CMU",
    role: "Full Stack Developer",
    skills: ["Node.js", "React", "MongoDB"],
    image: "https://i.pravatar.cc/150?u=2",
    description: "ชอบต่อ API และออกแบบ Database Schema",
    experience: "2 years",
  },
  {
    id: 3,
    firstName: "กิตติ",
    lastName: "ดีไซน์",
    city: "Nonthaburi",
    company: "Creative Agency",
    education: "KMUTT",
    role: "UI/UX Designer",
    skills: ["Figma", "CSS", "Adobe XD"],
    image: "https://i.pravatar.cc/150?u=3",
    description: "เน้นการออกแบบที่ผู้ใช้ใช้งานง่ายที่สุด",
    experience: "5 years",
  },
  {
    id: 4,
    firstName: "ธนา",
    lastName: "มั่นคง",
    city: "Bangkok",
    company: "Fintech Solutions",
    education: "Kasetsart University",
    role: "Backend Developer",
    skills: ["Go", "SQL", "Docker"],
    image: "https://i.pravatar.cc/150?u=4",
    description: "เชี่ยวชาญเรื่อง Microservices และ Performance",
    experience: "4 years",
  },
  {
    id: 5,
    firstName: "อารี",
    lastName: "เรียนรู้",
    city: "Phuket",
    company: "Startup Hub",
    education: "Mahidol University",
    role: "Frontend Developer",
    skills: ["Vue.js", "SASS", "JavaScript"],
    image: "https://i.pravatar.cc/150?u=5",
    description: "กำลังอินกับ Animation ในเว็บไซต์",
    experience: "1 year",
  },
  {
    id: 6,
    firstName: "ปกรณ์",
    lastName: "ใจดี",
    city: "Bangkok",
    company: "Global Tech",
    education: "Thammasat",
    role: "DevOps Engineer",
    skills: ["AWS", "Kubernetes", "CI/CD"],
    image: "https://i.pravatar.cc/150?u=6",
    description: "ดูแลเรื่องการ Deploy และ Scalability",
    experience: "6 years",
  },
  {
    id: 7,
    firstName: "นารี",
    lastName: "ยอดขยัน",
    city: "Khon Kaen",
    company: "SoftDev House",
    education: "KKU",
    role: "QA Automation",
    skills: ["Cypress", "Selenium", "Python"],
    image: "https://i.pravatar.cc/150?u=7",
    description: "Bug ต้องหมดไปจากโลกนี้!",
    experience: "2 years",
  },
  {
    id: 8,
    firstName: "ชัยยุทธ",
    lastName: "รวดเร็ว",
    city: "Bangkok",
    company: "E-commerce Giant",
    education: "KMITL",
    role: "Mobile Developer",
    skills: ["Flutter", "Dart", "Firebase"],
    image: "https://i.pravatar.cc/150?u=8",
    description: "สร้าง App สวยๆ ได้ทั้ง iOS และ Android",
    experience: "3 years",
  },
  {
    id: 9,
    firstName: "มณี",
    lastName: "สีนวล",
    city: "Chonburi",
    company: "Freelance",
    education: "BU",
    role: "Frontend Developer",
    skills: ["React", "Next.js", "Tailwind"],
    image: "https://i.pravatar.cc/150?u=9",
    description: "รักในการเขียน Clean Code",
    experience: "2 years",
  },
  {
    id: 10,
    firstName: "อาทิตย์",
    lastName: "สว่างจิต",
    city: "Bangkok",
    company: "Data Insight",
    education: "KMUTNB",
    role: "Data Engineer",
    skills: ["Python", "Spark", "SQL"],
    image: "https://i.pravatar.cc/150?u=10",
    description: "จัดการ Pipeline ข้อมูลขนาดใหญ่",
    experience: "4 years",
  },
  {
    id: 11,
    firstName: "สมหญิง",
    lastName: "จริงใจ",
    city: "Bangkok",
    company: "Agile Team",
    education: "Chulalongkorn",
    role: "Scrum Master",
    skills: ["Agile", "Jira", "Communication"],
    image: "https://i.pravatar.cc/150?u=11",
    description: "ช่วยให้ทีมทำงานได้ไหลลื่นที่สุด",
    experience: "5 years",
  },
  {
    id: 12,
    firstName: "เก่งกริช",
    lastName: "ว่องไว",
    city: "Samut Prakan",
    company: "Logistics Tech",
    education: "KMUTT",
    role: "Backend Developer",
    skills: ["Java", "Spring Boot", "PostgreSQL"],
    image: "https://i.pravatar.cc/150?u=12",
    description: "ถนัดงาน Enterprise Application",
    experience: "3 years",
  },
  {
    id: 13,
    firstName: "แพรวา",
    lastName: "สดใส",
    city: "Bangkok",
    company: "Design Studio",
    education: "Silpakorn",
    role: "Graphic Designer",
    skills: ["Photoshop", "Illustrator", "UI"],
    image: "https://i.pravatar.cc/150?u=13",
    description: "เน้นงาน Visual ที่โดดเด่น",
    experience: "2 years",
  },
  {
    id: 14,
    firstName: "มานะ",
    lastName: "อดทน",
    city: "Rayong",
    company: "Manufacturing IT",
    education: "Kasetsart",
    role: "Systems Analyst",
    skills: ["UML", "Requirements", "ERP"],
    image: "https://i.pravatar.cc/150?u=14",
    description: "วิเคราะห์ระบบให้ตอบโจทย์ธุรกิจ",
    experience: "7 years",
  },
  {
    id: 15,
    firstName: "จินดา",
    lastName: "พาสุข",
    city: "Pathum Thani",
    company: "HealthTech",
    education: "Mahidol",
    role: "Full Stack Developer",
    skills: ["Next.js", "Prisma", "Postgres"],
    image: "https://i.pravatar.cc/150?u=15",
    description: "ชอบสร้าง Product ที่มีคุณค่าต่อสังคม",
    experience: "3 years",
  },
  {
    id: 16,
    firstName: "วินัย",
    lastName: "รอบคอบ",
    city: "Bangkok",
    company: "Cyber Security Co.",
    education: "KMUTT",
    role: "Security Engineer",
    skills: ["Penetration Testing", "Linux", "Python"],
    image: "https://i.pravatar.cc/150?u=16",
    description: "ป้องกันระบบจากผู้ไม่หวังดี",
    experience: "4 years",
  },
  {
    id: 17,
    firstName: "ฟ้า",
    lastName: "สว่าง",
    city: "Phuket",
    company: "Travel Tech",
    education: "CMU",
    role: "Frontend Developer",
    skills: ["React Native", "Redux", "JS"],
    image: "https://i.pravatar.cc/150?u=17",
    description: "เชี่ยวชาญการทำ Cross-platform Apps",
    experience: "3 years",
  },
  {
    id: 18,
    firstName: "ยอดชาย",
    lastName: "กล้าหาญ",
    city: "Bangkok",
    company: "Game Studio",
    education: "KMITL",
    role: "Game Developer",
    skills: ["C#", "Unity", "3D Modeling"],
    image: "https://i.pravatar.cc/150?u=18",
    description: "สร้างโลกเสมือนจริงให้น่าตื่นเต้น",
    experience: "2 years",
  },
  {
    id: 19,
    firstName: "นภา",
    lastName: "สดใส",
    city: "Khon Kaen",
    company: "EdTech Startup",
    education: "KKU",
    role: "Product Owner",
    skills: ["Product Strategy", "User Research"],
    image: "https://i.pravatar.cc/150?u=19",
    description: "วาง Roadmap เพื่อพัฒนาผลิตภัณฑ์",
    experience: "4 years",
  },
  {
    id: 20,
    firstName: "สรวิชญ์",
    lastName: "พินิจ",
    city: "Bangkok",
    company: "Cloud Service",
    education: "Thammasat",
    role: "Site Reliability Engineer",
    skills: ["Terraform", "Go", "GCP"],
    image: "https://i.pravatar.cc/150?u=20",
    description: "ทำให้ระบบเสถียร 99.99%",
    experience: "5 years",
  },
];
